# action name
name: 'ossf-web-defn-check'

# action author
author: 'Simon Bennetts <psiinon@gmail.com>'

# action description
description: 'Checks if a repo has a valid Web Application Definition file.'

branding:
  icon: 'check'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - run: |
        echo $GITHUB_REPOSITORY
        git clone https://github.com/$GITHUB_REPOSITORY
        ls
        pip install pyyaml
      shell: bash
    - run: |
        import os
        import sys
        import yaml
        repo = os.environ['GITHUB_REPOSITORY']
        print('Repo is ' + repo)
        [owner,name] = repo.split('/')
        print('Name is ' + name)
        filename = './' + name + '/WebApp.yml'
        isFile = os.path.isfile(filename)
        print('Config file ' + filename + ' exists? ' + str(isFile))
        if not isFile:
          sys.exit(1)
        with open(filename, 'r') as stream:
          try:
            print(yaml.safe_load(stream))
          except yaml.YAMLError as exc:
            print(exc)
            sys.exit(1)
      shell: python
